modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "limitlessenchantments"
version = "${version}"
displayName = "Limitless Enchantments"
authors = "Thomas Darkson"
description = '''
Remove the enchanted book level limits in survival
'''
logoFile = "icon.png"

[[dependencies.limitlessenchantments]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.limitlessenchantments]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.limitlessenchantments]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
